### PR TITLE
Fix build failed without `desktop.blocks`

### PR DESCRIPTION
**Pull request by kompolom**

### CODE REVIEW

**Comment by qfox** [comment]
What build you trying to fix?

**Comment by kompolom** [comment]
tests failed without `desktop.blocks` folder

**Comment by qfox** [comment]
Oh, right. Can you also replace `bower-npm-install --non-interactive` with `bower install` in `npm run deps`?

**Comment by kompolom** [comment]
ok

**Comment by kompolom** [comment]
Is it possible to attach changes/commits to this PR?

**Comment by qfox** [comment]
Yeah, just push to your branch `bugfix/build`

**Comment by kompolom** [comment]
php failed with Travis... It works on localhost

**Comment by qfox** [comment]
@kompolom Yeah, it's because there is no php. Afaik we should switch env to php because node exists in any way and better to check templates under each php version than node.

Do you want to try it? https://github.com/bem/bh-php/blob/master/.travis.yml

**Comment by kompolom** [comment]
@zxqfox Done!

**Comment by qfox** [comment]
Rebased and merged into master via 5d84c86eb3c74ebf2b006bdc74eedb578cf57afc

**Pull request closed without merging**
